apiVersion: apps/v1
kind: Deployment
metadata:
  name: techsupportxpress
  labels:
    app: techsupportxpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techsupportxpress
  template:
    metadata:
      labels:
        app: techsupportxpress
    spec:
      containers:
        - name: techsupportxpress
          image: $GCR_REGISTRY/$GCP_PROJECT_ID/$DOCKER_IMAGE_NAME:$IMAGE_TAG  # Dynamic image tag
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: techsupportxpress-service
spec:
  selector:
    app: techsupportxpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

