version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techsupportxpress
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-app
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=techsupportxpress;user=myuser;password=mypassword
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
